name: Bug report
description: Report a reproducible problem in Dama King
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        **Security note:** If this is a security issue, please do not file it here. Follow `SECURITY.md`.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect to happen?
      placeholder: "When I click ... it ... but I expected ..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste any console errors, network errors, or screenshots.
      render: text
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Auth / Sign-in
        - Lobby / Create game
        - Matchmaking
        - Game room / Moves
        - Chat
        - Replay / History
        - Leaderboard / Stats
        - Docker / Deployment
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: "Chrome 121 / Safari 17 / Firefox 122"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 15 / Windows 11 / Ubuntu 24.04"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I can reproduce this issue consistently
          required: false
        - label: This is not a security vulnerability (I read `SECURITY.md`)
          required: false
